samples = ["SRR15618897", "SRR15618896"]
input_path = "/home/ahmed.isiaka/raw_data_exercise_20250219"

rule all:
    input:
        expand("results/fastqc/{sample}_raw_fastqc.html",
               sample=samples)

rule fastqc:
    input:
        lambda wildcards: f"{input_path}/{wildcards.sample}_raw.fastq"
    output:
        html="results/fastqc/{sample}_raw_fastqc.html",
        zip="results/fastqc/{sample}_raw_fastqc.zip"
    conda:
        "envs/rnaseq_preprocess.yaml"
    shell:
        """
        fastqc {input} --outdir results/fastqc
        """
