########################################
# Load configuration
########################################
configfile: "config/config.yaml"

samples = config["samples"]
input_path = config["input_path"]


########################################
# Include rule files
########################################
include: "rules/preprocess.smk"
include: "rules/alignment.smk"
include: "rules/count.smk"
include: "rules/multiqc.smk"


########################################
# Final target
########################################
rule all:
    input:
        "results/multiqc/multiqc_report.html"