samples:
  - SRR15618896
  - SRR15618897
  - SRR15618898
  - SRR15618899
  - SRR15618900

input_path: "/opt/students/ahmed.isiaka/raw_data_exercise_20260218"

genome_index_dir: "/opt/shared/SYSBIO/Mus_musculus.GRCm39/genome"

gtf_file: "/opt/shared/SYSBIO/Mus_musculus.GRCm39/genome.gtf"

multiqc_extra: "--verbose"